# Generated by Django 2.0 on 2019-01-31 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=100, unique=True)),
                ('flag', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Users'),
        ),
        migrations.AddField(
            model_name='customers',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tickets'),
        ),
    ]
