# Generated by Django 2.0 on 2019-01-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190131_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='domainName',
            new_name='domain_name',
        ),
    ]
