# Generated by Django 2.0 on 2019-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190131_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(default='10:10'),
        ),
        migrations.AddField(
            model_name='events',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.TextField(default='New Delhi'),
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.TimeField(default='10:10'),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default='1997-01-23'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(default='1997-01-23'),
        ),
    ]
