# Generated by Django 2.0 on 2019-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190131_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date',
            field=models.DateField(default='1997-01-23'),
        ),
    ]
